server:
  port: ${PORT:8761}

spring:
  application:
    name: lab-4-eureka-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0