#this can be used to use file on class path as a local repository
#spring:
#  profiles:
#    active: native

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maiorovi/ExternalConfigRepo